run:
	php artisan serve --host=0.0.0.0 --port=8001

migrate:
	php artisan migrate

seed:
	php artisan db:seed

fresh:
	php artisan migrate:fresh --seed

# Можно добавить alias на Composer
composer:
	composer install