services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wp_data:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
  
  laravel:
    image : php:8.2-cli
    working_dir: /var/www/laravel
    volumes:
      - ../laravel:/var/www/laravel
    ports:
      - "8001:8001"
    depends_on:
      - db
    # command: php artisan serve --host=0.0.0.0 --port=8001
    command: >
      bash -c "
        docker-php-ext-install pdo pdo_mysql &&
        php artisan serve --host=0.0.0.0 --port=8001
      "
  symfony-guide:
    image : php:8.2-cli
    working_dir: /var/www/symfony
    volumes:
      - ../symfony-guide:/var/www/symfony
    ports:
      - "8002:8002"
    depends_on:
      - db
    command: >
      bash -c "
        docker-php-ext-install pdo pdo_mysql &&
        curl -sS https://get.symfony.com/cli/installer | bash &&
        mv ~/.symfony*/bin/symfony /usr/local/bin/symfony &&
        symfony server:start --listen-ip=0.0.0.0 --port=8002 --no-tls
      "
